name: Block specific branch merge

on: 
  pull_request:
    branches:
      - main

jobs:
  block-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check branch name
      id: checkbranch
      run: |
        if [[ "${{ github.head_ref }}" == "test" ]]; then 
          echo "state=failure" >> $GITHUB_ENV
        else 
          echo "state=success" >> $GITHUB_ENV
        fi

    - name: Block merge from specific branch
      uses: actions/github-script@v3
      with:
        script: |
          const { owner, repo } = context.repo
          const { head } = context.payload.pull_request
          const { state } = process.env
    
          const check = {
            owner,
            repo,
            name: 'Block merge from test',
            head_sha: head.sha,
            status: 'completed',
            conclusion: state === 'failure' ? 'failure' : 'success',
            output: {
              title: 'Block merge from test',
              summary: state === 'failure' ? 'This pull request cannot be merged.' : 'This pull request can be merged.'
            }
          }
    
          await github.checks.create(check)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
